monolog:
    channels:
        - deprecation # Dédié aux avertissements de dépréciation

# Configuration pour l'environnement de développement
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stdout" # Rediriger vers stdout en développement
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            deprecation:
                type: stream
                path: "php://stdout" # Dépréciations également redirigées vers stdout
                channels: [deprecation]

# Configuration pour l'environnement de test
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log" # Fichier local pour les logs en test
                level: debug

# Configuration pour l'environnement de production
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # Empêche les fuites de mémoire en limitant les messages sauvegardés
            nested:
                type: stream
                path: "php://stdout" # Redirection vers stdout en production
                level: info
                formatter: monolog.formatter.json # Format JSON pour une analyse plus facile
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "php://stdout" # Dépréciations également vers stdout
                formatter: monolog.formatter.json
